POST http://localhost:4002/products 
content-type: application/json

{
    "name": "pomada",
    "price": 20
}

###

GET http://localhost:4002/products 

###

GET http://localhost:4002/products/2e60f8c6-6b36-47ca-9e28-2da52072e7c6

###

PUT http://localhost:4002/products/c01d1141-baac-44d2-a498-57774061a5be
Content-Type: application/json

{
    "price": 250
}

###
DELETE http://localhost:4002/products/abbdd383-b939-404d-974d-c0102116dda0